[project]
name = "omniversify-tts-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.136.1",
    "onnxruntime-rocm>=1.22.2.post1",
    "piper-tts>=1.4.2",
    "pydub>=0.25.1",
    "requests>=2.33.1",
    "sounddevice>=0.5.5",
    "soundfile>=0.13.1",
    "uvicorn>=0.46.0",
]
